name: publish-to-npm
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.4.0
    - name: Install pnpm
      uses: pnpm/action-setup@v4.4.0
    - name: Install Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: "22.23.1"
        registry-url: 'https://registry.npmjs.org/'
    - name: Install dependencies
      run: pnpm install
    - name: Publish package
      run: pnpm -r publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
